---
title: "thesis_non_maps"
output: html_notebook
---

```{r}

# functions located in another R sheet
source("thesis_code_functions.R")


```


```{r}

bk_count_2010 <- crimeCount(2010) # crime 
bk_count_2018 <- crimeCount(2018) # crime 

bk_gentri_2010 <- bkGentri(2010) # gentrification 
bk_gentri_2018 <- bkGentri(2018) # gentrification

bk_gen_all <- calcChange(bk_gentri_2010, bk_gentri_2018)

bk_gen_crime_all <- mergeTracts(bk_gen_all, bk_count_2010, bk_count_2018)


bkg_all <- calcScore(bk_gen_crime_all)
bkg_ct_all <- calcScore_CT(bk_gen_crime_all)


bkg_no_gentri <- bkg_all %>% 
  filter(NTA_GENTRI_SCORE < 0)
bkg_ct_no_gentri <- bkg_ct_all %>% 
  semi_join(bkg_no_gentri, by = "NTA_CODE")

nta_map_all <- toSpatial_NTA(bkg_all)
nta_map_ct_all <- toSpatial_tracts(bkg_ct_all)
nta_map_ct_no_gentri <- toSpatial_tracts(bkg_ct_no_gentri)


ntm_all <- plotMapGentri(nta_map_all, "2010", "2018")
ntm_no_gentri <- plotMapGentri(nta_map_no_gentri, "2010", "2018")

pmc_all <- plotMapCrime(nta_map_all, "2010", "2018")
pmc_no_gentri <- plotMapCrime(nta_map_no_gentri, "2010", "2018")

pmc_ct_all <- plotMapCrime(nta_map_ct_all, "2010", "2018")
pmc_ct_no_gentri <- plotMapCrime(nta_map_ct_no_gentri, "2010", "2018")

  ggplot(data = nta_map_ct_no_gentri) +
    geom_sf(aes(fill = FEL_CT_CHANGE), color = NA) +
    scale_fill_viridis_c(option = "viridis", name = "Change in Crime Rates", direction = -1) + 
    # labs(title = paste("\n", year_1, "-", year_2, "\n")) + 
    theme_map() + 
    theme(text = element_text(family = "raleway", size = 12), 
          plot.title = element_text(family = "jaapokki", size = 18))
  
  


cso_df <- cso %>% as.data.frame()


fel_change_2 <- cso_df %>% 
  filter(NTA_CODE %in% c("BK31", "BK34")) %>%
  group_by(FELONY_TYPE) %>%
  summarise(mean(OFN_NTA_CHANGE))
  
fel_change_all <- cso_df %>% 
  group_by(FELONY_TYPE) %>%
  summarise(mean(OFN_NTA_CHANGE))


ftypes <- ggplot() +
  geom_point(data = fel_change_all, aes(x = FELONY_TYPE, y = `mean(OFN_NTA_CHANGE)`, fill = "All Boroughs"), color = "black") + 
  geom_point(data = fel_change_2, aes(x = FELONY_TYPE, y = `mean(OFN_NTA_CHANGE)`, fill = "Bay Ride & Sunset Park"), color = "cyan4", alpha = 0.5) +
  # scale_fill_manual(values = c("darksalmon", "palegreen3", "honeydew3"), name = "Quadrant\nSignificance") +
  geom_hline(yintercept = 0, color = "grey70") + 
  coord_flip() +
  theme_minimal() +
  labs(title = "\nDifferent Types of Felonies among Boroughs",
      subtitle = "Change in Crime Rates (2010 - 2018)\n",
      y = "\nAverage Change in Crime Rate\n",
      x = "\nTypes of Felonies\n") +
  theme(text = element_text(family = "raleway", size = 12), 
        plot.title = element_text(family = "montserrat", size = 18))
  


# ggsave("visualizations/felony-types.svg", ftypes, width = 12, height = 5)


```

